# yaml-language-server: $schema=https://www.schemastore.org/pre-commit-config.json
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/mxab/pre-commit-trivy.git
    rev: v0.15.0
    hooks:
      - id: trivyfs-docker
        args:
          - --skip-dirs
          - ./tests
          - . # last arg indicates the path/file to scan
      - id: trivyconfig-docker
        args:
          - --skip-dirs
          - ./tests
          - . # last arg indicates the path/file to scan
  - repo: local
    hooks:
      - id: unit-test
        name: unit-test
        entry: python3 -m unittest discover
        language: python
        types: [python]
        pass_filenames: false
      - id: pytest
        name: pytest
        entry: python3 -m pytest
        language: python
        types: [python]
        additional_dependencies:
          - "pytest"
